# sources.yml
schema_version: "1.0"
mcp_name: "UAE Law MCP"
jurisdiction: "AE"

sources:
  - name: "UAE Ministry of Justice (Official Legislation Portal)"
    authority: "Ministry of Justice, United Arab Emirates"
    official_portal: "https://moj.gov.ae"
    canonical_identifier: "N/A (UAE legislation identified by Federal Decree-Law/Law number and year; no standardized URI scheme)"
    retrieval_method: "HTML_SCRAPE"
    api_documentation: "N/A"
    update_frequency: "monthly"
    last_ingested: "PENDING_FIRST_INGEST"
    license_or_terms:
      type: "Government Open Data"
      url: "https://moj.gov.ae"
      summary: "UAE federal legislation is publicly available through the Ministry of Justice portal; government publications are accessible for informational purposes"
    coverage:
      scope: "Federal Decree-Laws, Federal Laws, Cabinet Decisions, and ministerial resolutions including PDPL (45/2021), Cybercrimes Law (34/2021), Electronic Transactions Law (46/2021), Commercial Companies Law (2/2015), and related implementing regulations"
      limitations: "Emirate-level legislation not comprehensively covered; historical laws prior to digitization may be incomplete; implementing regulations may lag behind primary legislation; Arabic is the authoritative language — English translations are unofficial unless from DIFC/ADGM"
    languages:
      - "ar"
      - "en"

  - name: "DIFC Laws and Regulations"
    authority: "Dubai International Financial Centre (DIFC)"
    official_portal: "https://difclaws.com"
    canonical_identifier: "DIFC Law No. [number]/[year]"
    retrieval_method: "HTML_SCRAPE"
    api_documentation: "N/A"
    update_frequency: "on_change"
    last_ingested: "PENDING_FIRST_INGEST"
    license_or_terms:
      type: "Government Open Data"
      url: "https://difclaws.com/terms"
      summary: "DIFC laws and regulations are published in English and freely accessible; DIFC is a common-law jurisdiction within Dubai with its own courts and regulatory framework"
    coverage:
      scope: "DIFC Data Protection Law (Law No. 5/2020), DIFC Operating Law, DIFC Companies Law, DIFC Employment Law, DIFC Insolvency Law, DIFC Arbitration Law, and all DIFC regulations and rules of court"
      limitations: "Only covers DIFC free zone laws; does not include Dubai or UAE federal legislation; DIFC court decisions not fully indexed"
    languages:
      - "en"

  - name: "ADGM Legal Framework"
    authority: "Abu Dhabi Global Market (ADGM)"
    official_portal: "https://adgm.com/legal-framework"
    canonical_identifier: "ADGM Regulations [year]"
    retrieval_method: "HTML_SCRAPE"
    api_documentation: "N/A"
    update_frequency: "on_change"
    last_ingested: "PENDING_FIRST_INGEST"
    license_or_terms:
      type: "Government Open Data"
      url: "https://adgm.com/legal-framework"
      summary: "ADGM laws and regulations are published in English and freely accessible; ADGM is a common-law jurisdiction within Abu Dhabi with its own courts and regulatory framework"
    coverage:
      scope: "ADGM Data Protection Regulations 2021, ADGM Companies Regulations, ADGM Financial Services regulations, ADGM Employment Regulations, and all ADGM guidance and rules"
      limitations: "Only covers ADGM free zone laws; does not include Abu Dhabi emirate or UAE federal legislation; ADGM court decisions not fully indexed"
    languages:
      - "en"

  - name: "WAM (Emirates News Agency) — Official Gazette"
    authority: "Emirates News Agency (WAM)"
    official_portal: "https://www.wam.ae"
    canonical_identifier: "N/A (gazette notices by date and number)"
    retrieval_method: "HTML_SCRAPE"
    api_documentation: "N/A"
    update_frequency: "weekly"
    last_ingested: "PENDING_FIRST_INGEST"
    license_or_terms:
      type: "Government Publication"
      url: "https://www.wam.ae"
      summary: "Official UAE government news and gazette publications; WAM is the official state news agency and publishes legislative announcements"
    coverage:
      scope: "Official government gazette notices, promulgation announcements for new Federal Decree-Laws, and regulatory updates"
      limitations: "Not a structured legal database; primarily news announcements; full legal texts must be obtained from MOJ or official gazette"
    languages:
      - "ar"
      - "en"

data_freshness:
  automated_checks: true
  check_frequency: "weekly"
  last_verified: "PENDING_FIRST_INGEST"

# Notes:
# - UAE has a complex multi-layered legal system: Federal law applies across all
#   emirates, but free zones (DIFC in Dubai, ADGM in Abu Dhabi) have their own
#   independent legal systems based on common law (English language)
# - The federal Personal Data Protection Law (PDPL, Federal Decree-Law No. 45/2021)
#   is the overarching data protection framework, effective January 2, 2022
# - DIFC Data Protection Law (Law No. 5/2020) and ADGM Data Protection Regulations 2021
#   are separate regimes that apply within their respective free zones
# - The UAE Data Office (established 2022) oversees implementation of the federal PDPL
# - Arabic is the official legal language for federal legislation; DIFC and ADGM laws
#   are natively drafted in English
# - The Cybercrimes Law (Federal Decree-Law No. 34/2021) replaced the older
#   Federal Decree-Law No. 5/2012 on Combating Cybercrimes
# - Telecommunications Regulatory Authority (TRA, now TDRA) regulates ICT sector
# - Critical for Ansvar's Middle East market expansion
